### ISSUE TITLE
Permission_Denied issue when triggering sms from firestore

### ISSUE THREAD

**Issue by jorgror** [twilio-labs/twilio-firebase-extensions#65]
I have installed the Twilio Firebase extention and configured it with my trail account SID, Auth token, phone number and colletion. When adding a document containing fields "to" and "body", nothing happens. When checking the Cloud Logs, I discovered this error. I'm not able to see what permissions is missing.

```
{
  "textPayload": "Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.\n    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:189:52)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)\n    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)\n    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78\n    at processTicksAndRejections (internal/process/task_queues.js:77:11) {\n  code: 7,\n  details: 'Missing or insufficient permissions.',\n  metadata: Metadata { internalRepr: Map(0) {}, options: {} },\n  note: 'Exception occurred in retry method that was not classified as transient'\n}",
  "insertId": "645807860002b2affa06249e",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "my-project-name",
      "function_name": "ext-send-message-tt0s-processQueue",
      "region": "us-central1"
    }
  },
  "timestamp": "2023-05-07T20:18:14.176815Z",
  "severity": "ERROR",
  "labels": {
    "instance_id": "00c61b117ceaff89eb1d95d2fcd877055dc0ff811dfd78f4be9853fd017ebb9fffc2f0775c68df1143c48a19e1b0bf83b727f746b81dc451b0",
    "execution_id": "xvf22xw2r3im"
  },
  "logName": "projects/my-project-name/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/my-project-name/traces/deac5ebb0389ebfa5ac638d43878e307",
  "receiveTimestamp": "2023-05-07T20:18:14.300457108Z"
}
```

**Comment by jorgror** [comment]
I think there was some issue with Firebase Extensions this weekend which has been resolved. I reinstalled twilio firebase today, and now it works as expected.
